commonStep: &commonStep
  step:
    caches:
      - composer

    script:
      - apt-get update && apt-get install -y unzip   nodejs npm librdkafka-dev
      - pecl install swoole
      - pecl install rdkafka
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - docker-php-ext-install pcntl
      - echo "extension=swoole.so" > /usr/local/etc/php/conf.d/docker-php-swoole.ini
      - echo "extension=rdkafka.so" > /usr/local/etc/php/conf.d/docker-php-rdkafka.ini
      - composer install 
      - cp .env.pipeline .env
      - php artisan key:generate
      - php artisan view:clear
      - php artisan cache:clear
      - npm install
      - npm run dev
    artifacts:
      - storage/**
      - vendor/**
      - public/**
      - node_modules/**
      - .env
    services:
      - postgres

commonScript: &commonScript
  script:
    - echo "common script"
image: php:7.2-fpm
pipelines:
  branches:
    aws-deployment: 
    - step:
    - <<: *commonStep
 


definitions:
      services:
        postgres:
            image: postgres
            environment:
                POSTGRES_USER: 'postgres'
                POSTGRES_PASSWORD: 'testuser'
                POSTGRES_DB: 'test'        