commonBuild: &commonBuild
  script:
    - apt-get update && apt-get install -y unzip   nodejs npm librdkafka-dev postgresql-client libmcrypt-dev   libpq-dev
    - pecl install swoole
    - pecl install rdkafka
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - docker-php-ext-install pdo pdo_pgsql pcntl
    - echo "extension=swoole.so" > /usr/local/etc/php/conf.d/docker-php-swoole.ini
    - echo "extension=rdkafka.so" > /usr/local/etc/php/conf.d/docker-php-rdkafka.ini
    - composer config -g github-oauth.github.com 5b8e5c78c1de03fc833d8a86a15bc9b6c3a3fea1
    - composer install 
    - cp .env.pipeline .env
    - php artisan key:generate
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan migrate
    - npm install
    - npm install --save babel-helper-vue-jsx-merge-props
    - npm run dev
  artifacts:
    - storage/**
    - vendor/**
    - public/**
    - node_modules/**
    - .env
  services:
    - postgres

commonUnittest_pipeline: &commonUnittest_pipeline
  script:
    - apt-get update && apt-get install -y libmcrypt-dev   libpq-dev postgresql-client librdkafka-dev
    - pecl install swoole
    - pecl install rdkafka
    - echo "extension=swoole.so" > /usr/local/etc/php/conf.d/docker-php-swoole.ini
    - echo "extension=rdkafka.so" > /usr/local/etc/php/conf.d/docker-php-rdkafka.ini
    - docker-php-ext-install pdo pdo_pgsql pcntl
    - psql -U "postgres" -h "localhost"  -p 5432 -c "CREATE DATABASE test_crm"
    - php artisan migrate
    - php artisan passport:install
    - ./vendor/bin/phpunit
  services:
    - postgres

commonUnittest: &commonUnittest
  script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - cat .develop_hosts >> ~/.ssh/known_hosts
    - (umask  077 ; echo $devkey2 | base64 --decode > ~/.ssh/id_rsa)
    - ssh $devuser36@ninepinetechnology-tmcrjvwbpr.dynamic-m.com -p 9913 'bash -i  "unit-test.sh"'



image: php:7.3-fpm
pipelines:
  branches:
    develop: 
    - step:
        name: Develop
        caches:
          - composer
        <<: *commonBuild
    - step:
        name: Unit test
        <<: *commonUnittest
    - step:
        name: Deploy to AWS
        script:
          - apt-get update && apt-get install -y openssh-client
          - mkdir -p ~/.ssh
          - cat .uat_host >> ~/.ssh/known_hosts
          - (umask  077 ; echo $awskey | base64 --decode > ~/.ssh/id_rsa)
          
          - ssh $awsuser@9pineuat.com 'bash -i  "compile.sh"'      

    develop-local: 
    - step:
        caches:
          - composer
        name: Develop
        <<: *commonBuild
    - step:
        name: Unit test
        <<: *commonUnittest
    - step:
        name: Deploy to develop
        script:
          - apt-get update && apt-get install -y openssh-client
          - mkdir -p ~/.ssh
          - cat .develop_hosts >> ~/.ssh/known_hosts
          - (umask  077 ; echo $devkey2 | base64 --decode > ~/.ssh/id_rsa)
          - ssh $devuser36@ninepinetechnology-tmcrjvwbpr.dynamic-m.com -p 9913 'bash -i  "compile.sh"'

 


definitions:
      services:
        postgres:
            image: postgres
            environment:
                POSTGRES_USER: 'postgres'
                POSTGRES_PASSWORD: 'testuser'
                POSTGRES_DB: 'test'        